---
title: "Bayesian CNDC Example"
author: "Michael Culshaw-Maurer"
date: "1/13/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(brms)
library(tidyverse)
library(tidybayes)
library(parallel)

theme_set(theme_bw())
```

```{r}
d <- read_csv("https://raw.githubusercontent.com/bohm0072/cndc_bayesian_eval/main/minimal_example/data/mn_two_varieties.csv?token=ADZFJGWDUSC36CHCWQIEX7DABC4PG")

```

```{r}
nl_form <- bf(W ~ fmin(Bmax + Si * (N - (alpha1*(Bmax^(-alpha2)))), Bmax),
           Bmax + Si ~ 1 + (1|index),
           alpha1 + alpha2 ~ 1 + (1|group),
           nl = T)

nl_prior <- c(set_prior("normal(5.2,0.1)", class = "sd", nlpar = "Bmax", group = "index"),
         set_prior("normal(1.2,0.1)", class = "sd", nlpar = "Si", group = "index"),
         set_prior("normal(0.05,0.01)", nlpar = "alpha1", class = "sd", group ="group"),
         set_prior("normal(0.13,0.01)", nlpar = "alpha2", class = "sd", group ="group"),
         set_prior("normal(11.0,0.1)", nlpar = "Bmax", lb = 1),
         set_prior("normal(5.0,0.3)", nlpar = "Si", lb = 0),
         set_prior("normal(5.0,0.1)", nlpar = "alpha1", lb = 0),
         set_prior("normal(0.35,0.01)", nlpar = "alpha2", lb = 0, ub = 1),
         set_prior("student_t(3,1.3,0.1)", class = "sigma"))
```


```{r}
model <- brm(formula = nl_form, 
    data = d, 
    prior = nl_prior,
    iter = 5000, warmup = 2000,
    control = list(adapt_delta = 0.99),
    chains = 4, cores = detectCores())
```

```{r}
fmin <- function(x,y){
  pmin(x,y)
}
```

```{r}
summary(model)
```

```{r}
posterior_samples(model) %>% 
  pivot_longer(starts_with("b")) %>% 
  filter(name != "lp__") %>% 
  ggplot(aes(x = value, y = name)) +
  geom_vline(xintercept = 0, linetype = 2, color = "gray90") +
  stat_halfeye()
```

```{r}
model %>%
  spread_draws(b_alpha2_Intercept, r_group__alpha2[group,]) %>%
  mutate(group_alpha2 = b_alpha2_Intercept + r_group__alpha2,
         group = factor(group)) %>%
  #compare_levels(group_alpha2, by = group) %>%
  ggplot(aes(x = group_alpha2, y = group)) +
  geom_halfeyeh()
```

```{r}
calc_nc <- function(W = seq(from = 1, to = 10, length.out = 100), alpha1, alpha2){
  Nc <- alpha1*(W^(-alpha2))
  d <- tibble(Nc = Nc, W = W)
  return(d)
}
```

```{r}
alphas <- model %>% 
  spread_draws(b_alpha1_Intercept, r_group__alpha1[group,], n = 100, seed = 1) %>% 
  mutate(group_alpha1 = b_alpha1_Intercept + r_group__alpha1) %>% 
  left_join(
    model %>% 
      spread_draws(b_alpha2_Intercept, r_group__alpha2[group,], n = 100, seed = 1) %>% 
      mutate(group_alpha2 = b_alpha2_Intercept + r_group__alpha2) 
  ) %>% 
  select(.draw, group, group_alpha1, group_alpha2)
```

```{r}
alphas <- alphas %>% 
  rowwise() %>% 
  mutate(values = list(calc_nc(W = seq(from = 1, to = 30, length.out = 3000), alpha1 = group_alpha1, alpha2 = group_alpha2))) %>% 
  unnest(values)
```

```{r}
alphas %>% 
  mutate(group = factor(group)) %>% 
  ggplot(aes(x = W, y = Nc, color = group, group = interaction(.draw, group))) +
  geom_line(alpha = 0.2) +
  scale_color_viridis_d() +
  theme_minimal()
```

```{r}
alphas %>% 
  mutate(group = factor(group)) %>% 
  group_by(group, W) %>% 
  median_hdci(Nc) %>% 
  ggplot(aes(x = W, y = Nc, color = group, fill = group)) +
  geom_ribbon(aes(ymin = .lower, ymax = .upper), alpha = 0.2, color = NA) +
  geom_line() +
  scale_color_viridis_d() +
  scale_fill_viridis_d() +
  theme_minimal()
```

```{r}
alphas %>% 
  select(-group_alpha1, -group_alpha2) %>% 
  mutate(group = factor(group)) %>% 
  pivot_wider(names_from = group, values_from = Nc) %>% 
  mutate(diff = `3` - `7`) %>% 
  select(.draw, W, diff) %>% 
  group_by(W) %>% 
  median_hdci(diff) %>% 
  ggplot(aes(x = W, y = diff)) +
  geom_ribbon(aes(ymin = .lower, ymax = .upper), alpha = 0.2, color = NA) +
  geom_line() +
  theme_minimal() +
  labs(y = "Diff in Nc between MN Russet Burbank and MN Easton")
```

Should add the simplest way to put plateau fits onto the curves here

